// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d55578e4ba98506a, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type FindResponse struct {
	Vessel               *Vessel  `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d55578e4ba98506a, []int{1}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_d55578e4ba98506a, []int{2}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Vessel)(nil), "vessel.Vessel")
	proto.RegisterType((*FindResponse)(nil), "vessel.FindResponse")
	proto.RegisterType((*Specification)(nil), "vessel.Specification")
}

func init() { proto.RegisterFile("proto/vessel.proto", fileDescriptor_d55578e4ba98506a) }

var fileDescriptor_d55578e4ba98506a = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbf, 0xcd, 0xd7, 0xc6, 0x64, 0x34, 0x3d, 0x0c, 0x0a, 0x6b, 0x51, 0x08, 0x39, 0x48,
	0x4e, 0x15, 0x2a, 0x78, 0x14, 0xbc, 0x08, 0x7a, 0x11, 0x52, 0xd0, 0x63, 0xd9, 0x26, 0xa3, 0x0e,
	0x24, 0xd9, 0x90, 0x84, 0xb4, 0xfe, 0x1b, 0x7f, 0xaa, 0x38, 0x69, 0xaa, 0xf5, 0xe0, 0x6d, 0xde,
	0x77, 0xd9, 0xd9, 0xe7, 0x61, 0x01, 0xab, 0xda, 0xb6, 0xf6, 0xb2, 0xa3, 0xa6, 0xa1, 0x7c, 0x26,
	0x01, 0xdd, 0x3e, 0x45, 0x1f, 0x0a, 0xdc, 0x27, 0x19, 0x71, 0x02, 0x0e, 0x67, 0x5a, 0x85, 0x2a,
	0xf6, 0x13, 0x87, 0x33, 0x9c, 0x82, 0x97, 0x9a, 0xca, 0xa4, 0xdc, 0xbe, 0x6b, 0x27, 0x54, 0xf1,
	0x38, 0xd9, 0x65, 0x3c, 0x07, 0x28, 0xcc, 0x66, 0xb9, 0x26, 0x7e, 0x7d, 0x6b, 0xf5, 0x7f, 0x39,
	0xf5, 0x0b, 0xb3, 0x79, 0x96, 0x02, 0x11, 0x46, 0xa5, 0x29, 0x48, 0x8f, 0x64, 0x99, 0xcc, 0x78,
	0x06, 0xbe, 0xe9, 0x0c, 0xe7, 0x66, 0x95, 0x93, 0x1e, 0x87, 0x2a, 0xf6, 0x92, 0xef, 0x02, 0x4f,
	0xc1, 0xb3, 0xeb, 0x92, 0xea, 0x25, 0x67, 0xda, 0x95, 0x5b, 0x07, 0x92, 0xef, 0xb3, 0xe8, 0x1a,
	0x8e, 0xee, 0xb8, 0xcc, 0x12, 0x6a, 0x2a, 0x5b, 0x36, 0x84, 0x17, 0xb0, 0x85, 0x17, 0xd6, 0xc3,
	0xf9, 0x64, 0xb6, 0x35, 0xeb, 0x3d, 0x92, 0x41, 0xed, 0x01, 0x82, 0x45, 0x45, 0x29, 0xbf, 0x70,
	0x6a, 0x5a, 0xb6, 0xe5, 0x9e, 0x90, 0xfa, 0x53, 0xc8, 0xf9, 0x25, 0x34, 0x7f, 0x84, 0xa0, 0xdf,
	0xbe, 0xa0, 0xba, 0xe3, 0x94, 0xf0, 0x06, 0x82, 0x2f, 0xa8, 0xdb, 0x9d, 0xc0, 0xc9, 0x40, 0xb1,
	0xf7, 0xe6, 0xf4, 0x78, 0xa8, 0x7f, 0x2a, 0x44, 0xff, 0x56, 0xae, 0x7c, 0xc3, 0xd5, 0x67, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x68, 0x75, 0x76, 0x49, 0x9c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*FindResponse, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*FindResponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(FindResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *Specification, *FindResponse) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *FindResponse) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}
